name: "web_app"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "10.10.38.169"
  port: 3306
  user: "root"
  password: "dreame@2021"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 150
redis:
  host: "10.10.38.169"
  port: 16379
  db: 0
